#!/usr/bin/env bash
set -Eeuo pipefail

# Local HTTPS reference control-plane smoke; reference servers are test doubles.
repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
go_bin=${GO_BIN:-go}; registry_port=${AFH_REF_REGISTRY_PORT:-19443}; gateway_port=${AFH_REF_GATEWAY_PORT:-19444}; provider_port=${AFH_REF_PROVIDER_PORT:-19441}; hub_port=${AFH_REF_HUB_PORT:-19442}; tenant=${AFH_REF_TENANT:-reference-smoke}
run_dir=$(mktemp -d -t afh-control-plane.XXXXXX); hub_bin="$run_dir/hub"; provider_bin="$run_dir/provider"; registry_bin="$run_dir/registry"; gateway_bin="$run_dir/gateway"; hub_pid=""; provider_pid=""; registry_pid=""; gateway_pid=""
log() { printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$*"; }
fail() { printf '\nERROR: %s\n' "$*" >&2; for f in "$run_dir"/*.log; do [[ -f "$f" ]] && { printf '\n--- %s ---\n' "$f" >&2; tail -n 100 "$f" >&2; }; done; exit 1; }
cleanup() { local status=$?; trap - EXIT INT TERM; for p in "$hub_pid" "$gateway_pid" "$registry_pid" "$provider_pid"; do [[ -n "$p" ]] && kill "$p" 2>/dev/null || true; done; wait "$hub_pid" "$gateway_pid" "$registry_pid" "$provider_pid" 2>/dev/null || true; rm -rf -- "$run_dir"; exit "$status"; }
trap cleanup EXIT INT TERM
for command_name in curl jq openssl; do command -v "$command_name" >/dev/null || fail "$command_name is required"; done
if [[ "$go_bin" == */* ]]; then [[ -x "$go_bin" ]] || fail "Go binary is not executable: $go_bin"; else command -v "$go_bin" >/dev/null || fail "Go binary not found: $go_bin"; fi
cd "$repo_root"; log "Building Hub, Provider, Registry, and Gateway reference binaries"; "$go_bin" build -o "$hub_bin" ./cmd/federation-hub; "$go_bin" build -o "$provider_bin" ./cmd/a2a-go-fixture; "$go_bin" build -o "$registry_bin" ./cmd/reference-registry; "$go_bin" build -o "$gateway_bin" ./cmd/reference-gateway
log "Generating one-day local TLS certificate"; openssl req -x509 -newkey rsa:2048 -nodes -days 1 -keyout "$run_dir/tls.key" -out "$run_dir/tls.crt" -subj '/CN=127.0.0.1' -addext 'subjectAltName=IP:127.0.0.1' >/dev/null 2>&1 || fail "openssl certificate generation failed"
printf '%s\n' 'schema_version: 1' 'defaults:' '  protocol:' '    kind: a2a' '    profiles:' '      - protocol_version: "1.0"' '        binding: JSONRPC' '        stream_transport: SSE' '  discovery:' '    refresh_interval_seconds: 2' '    max_card_bytes: 262144' '    require_https: false' '    allow_private_urls: true' '  execution:' '    remote_timeout_seconds: 30' '    task_timeout_seconds: 60' '    max_retries: 1' '    cancel_grace_seconds: 5' '    reconnect: true' '  limits:' '    max_concurrent_tasks: 4' '    max_artifact_bytes: 10485760' 'agents:' '  - id: reference-agent' "    tenant_id: $tenant" '    display_name: Reference Agent' '    enabled: true' "    card_url: http://127.0.0.1:$provider_port/.well-known/agent-card.json" >"$run_dir/agent_config.yaml"
"$provider_bin" -listen "127.0.0.1:$provider_port" -public-url "http://127.0.0.1:$provider_port" >"$run_dir/provider.log" 2>&1 & provider_pid=$!
"$registry_bin" -listen "127.0.0.1:$registry_port" -tls-cert-file "$run_dir/tls.crt" -tls-key-file "$run_dir/tls.key" -token registry-secret >"$run_dir/registry.log" 2>&1 & registry_pid=$!
"$gateway_bin" -listen "127.0.0.1:$gateway_port" -tls-cert-file "$run_dir/tls.crt" -tls-key-file "$run_dir/tls.key" -token gateway-secret >"$run_dir/gateway.log" 2>&1 & gateway_pid=$!
wait_url() { local u=$1 label=$2; for _ in $(seq 1 200); do curl --fail --silent --max-time 1 "$u" >/dev/null && { log "$label ready"; return; }; sleep 0.1; done; fail "$label did not become ready: $u"; }
wait_url "http://127.0.0.1:$provider_port/.well-known/agent-card.json" Provider; for endpoint in "https://127.0.0.1:$registry_port/healthz" "https://127.0.0.1:$gateway_port/healthz"; do for _ in $(seq 1 200); do curl --fail --silent --insecure "$endpoint" >/dev/null && break; sleep 0.1; done; done
log "Checking Registry missing-Bearer rejection"; set +e; curl --silent --show-error --insecure -o /dev/null -w '%{http_code}' "https://127.0.0.1:$registry_port/v1/agents?tenant_id=$tenant" >"$run_dir/registry.status"; status=$(cat "$run_dir/registry.status"); set -e; [[ "$status" == 401 ]] || fail "Registry accepted missing Bearer token (HTTP $status)"
log "Starting Hub with external Registry publication/import and Gateway routing"; REGISTRY_TOKEN=registry-secret GATEWAY_TOKEN=gateway-secret "$hub_bin" -listen "127.0.0.1:$hub_port" -journal "$run_dir/hub.journal" -agent-config "$run_dir/agent_config.yaml" -auth-mode development -allow-private-agent-urls -credential-env-allowlist REGISTRY_TOKEN,GATEWAY_TOKEN -registry-url "https://127.0.0.1:$registry_port" -registry-ca-file "$run_dir/tls.crt" -registry-token-ref REGISTRY_TOKEN -registry-import-tenants "$tenant" -registry-sync-interval 1s -gateway-url "https://127.0.0.1:$gateway_port" -gateway-ca-file "$run_dir/tls.crt" -gateway-token-ref GATEWAY_TOKEN >"$run_dir/hub.log" 2>&1 & hub_pid=$!
wait_url "http://127.0.0.1:$hub_port/healthz" Hub
external=$(curl --fail --silent --insecure -H 'Authorization: Bearer registry-secret' "https://127.0.0.1:$registry_port/v1/agents?tenant_id=$tenant"); printf '%s\n' "$external" | jq .; jq -e 'length == 1 and .[0].id == "reference-agent"' <<<"$external" >/dev/null || fail "external Registry did not receive Agent"
local=$(curl --fail --silent -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/agents"); printf '%s\n' "$local" | jq .; jq -e 'length == 1 and .[0].id == "reference-agent"' <<<"$local" >/dev/null || fail "Hub local Agent cache is empty"
log "Checking Gateway missing-Bearer rejection"; set +e; status=$(curl --silent --show-error --insecure -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' --data '{}' "https://127.0.0.1:$gateway_port/v1/proxy/send"); set -e; [[ "$status" == 401 ]] || fail "Gateway accepted missing Bearer token (HTTP $status)"
log "Submitting INPUT_REQUIRED Task through configured HTTPS Gateway"; task=$(curl --fail-with-body --silent --show-error -X POST -H 'Content-Type: application/json' -H "X-AFH-Tenant-ID: $tenant" --data '{"agentId":"reference-agent","text":"input-required"}' "http://127.0.0.1:$hub_port/v1/tasks"); printf '%s\n' "$task" | jq .; task_id=$(jq -r '.id' <<<"$task"); jq -e '.delivery == "ACKNOWLEDGED" and (.remoteTaskId | length > 0)' <<<"$task" >/dev/null || fail "Gateway Task was not acknowledged"
log "Reconciling through Gateway to exercise Get/Subscribe forwarding"; set +e; reconciled=$(curl --fail-with-body --silent --show-error -X POST -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/tasks/$task_id/reconcile?subscribe=true" 2>&1); reconcile_status=$?; set -e; [[ $reconcile_status -ne 0 ]] || fail "paused Provider unexpectedly accepted an active Subscribe"; printf '%s\n' "$reconciled" | sed -n '1,8p'; paused=$(curl --fail --silent -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/tasks/$task_id"); jq -e '.state == "INPUT_REQUIRED" and (.remoteTaskId | length > 0) and (.remoteContextId | length > 0)' <<<"$paused" >/dev/null || fail "Gateway reconciliation did not preserve INPUT_REQUIRED"
log "Continuing the same remote Task/Context through Gateway"; continued=$(curl --fail-with-body --silent --show-error -X POST -H 'Content-Type: application/json' -H "X-AFH-Tenant-ID: $tenant" --data '{"text":"artifact-data"}' "http://127.0.0.1:$hub_port/v1/tasks/$task_id/messages") || fail "Gateway continuation failed"; printf '%s\n' "$continued" | jq .; jq -e '.delivery == "ACKNOWLEDGED" and (.remoteTaskId | length > 0) and (.remoteContextId | length > 0)' <<<"$continued" >/dev/null || fail "Gateway continuation lost remote IDs"
log "Reconciling the resumed Task through Gateway"; final_reconciled=$(curl --fail-with-body --silent --show-error -X POST -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/tasks/$task_id/reconcile?subscribe=true") || fail "Gateway resumed reconciliation failed"; printf '%s\n' "$final_reconciled" | jq .
for _ in $(seq 1 100); do final=$(curl --fail --silent -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/tasks/$task_id"); [[ $(jq -r '.state' <<<"$final") == COMPLETED ]] && break; sleep 0.1; done; jq -e '.state == "COMPLETED" and ([.artifacts[]?] | length > 0)' <<<"$final" >/dev/null || fail "Gateway Task did not complete"
grep -q 'proxy operation=get' "$run_dir/gateway.log" || fail "Gateway did not receive Get"
grep -q 'proxy operation=subscribe' "$run_dir/gateway.log" || fail "Gateway did not receive Subscribe"
log "Stopping Registry and proving Hub local cache remains available"; kill "$registry_pid" 2>/dev/null || true; wait "$registry_pid" 2>/dev/null || true; cached=$(curl --fail --silent -H "X-AFH-Tenant-ID: $tenant" "http://127.0.0.1:$hub_port/v1/agents"); jq -e 'length == 1 and .[0].healthStatus == "HEALTHY"' <<<"$cached" >/dev/null || fail "Hub cache was lost during Registry outage"; log "Registry/Gateway control-plane smoke passed: TLS, Bearer auth, publication, import, routing, and stale-cache behavior"
